### ISSUE TITLE
Use fieldrefs in tests

### ISSUE THREAD

**Issue by untergeek** [logstash-plugins/logstash-codec-es_bulk#2]
Per @jordansissel comment in original push.

**Comment by jsvd** [comment]
For anyone wishing to take care of this, it's essentially changing all lines that use nested hash references such as:

`insist { event['@metadata']['_id'] } == "1"`

 to use field references, like:

`insist { event["[@metadata][_id]"] } == "1"`

**Comment by untergeek** [comment]
Pretty sure this has been taken care of.
