### ISSUE TITLE
Parsing fails on `NaN` float value

### ISSUE THREAD

**Issue by baracoder** [logstash-plugins/logstash-codec-es_bulk#22]
**Logstash information**:

1. Logstash version: 7.16.1
2. Logstash installation source docker
3. How is Logstash being run kubernetes
4. How was the Logstash Plugin installed `RUN logstash-plugin install logstash-codec-es_bulk`

**Description of the problem including expected versus actual behavior**:

A program submits `NaN` as a numeric value. The parsing of the document fails and because it happens in the input, there is no way (at least that I am aware of) to manipulate the document to workaround this.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) pipeline definition(s), settings, locale, etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Submit a document with a field set to `NaN` e.g. `{ "threshold":NaN }`

**Provide logs (if relevant)**:

```
JSON parse failure. ES Bulk messages must in be UTF-8 JSON {:error=>#<LogStash::Json::ParserError: Non-standard token 'NaN': enable JsonParser.Feature.ALLOW_NON_NUMERIC_NUMBERS to allow
```

**Comment by andsel** [comment]
The provided JSON seems not valid, checked with [online tool](https://www.freeformatter.com/json-validator.html) for example, and report a violation of RFC 4627. 
Is this JSON coming from a real Elasticsearch instance?
Please, could you share the input part of your pipeline's configuration,?

**Comment by baracoder** [comment]
Actually the input is coming from a dotnet program using SeriLog to submit structured logs. logstash is between the program and the real elasticsearch instance to clean up the logs.
```
input {
  http {
    port => 9200
    # Override additional codecs, default would contain only "json"
    additional_codecs => { "application/json" => "es_bulk" }
    codec => "json"
  }
}
```
Maybe the problem is on the other side: There is a ticket in the serilog project, which is fixed several years ago https://github.com/serilog/serilog/pull/887 I will check if we have an outdated version.

**Comment by baracoder** [comment]
Turned out to be a bug in the application. Sorry for the noise.
