### ISSUE TITLE
Need Jenkins job for es_bulk codec to be tested, built

### ISSUE THREAD

**Issue by untergeek** [logstash-plugins/logstash-codec-es_bulk#3]
This was requested by @suyograo so he could get this assigned.

**Comment by purbon** [comment]
@untergeek @suyograo I check our jenkins and there is a job http://build-eu-00.elastic.co/view/LS%20Codecs/job/logstash_plugin_codec_es_bulk/ running this test, so we might like to close this issue, right?

**Comment by untergeek** [comment]
Yep!
