### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by Hronom** [logstash-plugins/logstash-codec-es_bulk#8]
Just after one message freezes and don't send's events...
`logstash-codec-es_bulk-2.0.4`

**Comment by Hronom** [comment]
My fault, forgot to add line ending at the end... so payload must looks like:
```
{"index":{"_index":"test_results","_type":"messages","_id":"1"}}\n
{"message":"test_text_1"}\n
```
without last `\n` message eaten by logstash but don't decoded by `es_bulk`, I think there must be some warning in console, this can prevent stupid mistakes...

**Comment by untergeek** [comment]
If this is resolved, can you please close it?

**Comment by colinsurprenant** [comment]
I don't know how this can be logged; this codec handles data line-by-line and thus cannot do anything until a line break is found. To add any kind of warning would require adding timers for line break detection which would be adding lots of complexity for very little value. 

Closing. Please feel free to reopen if needed.
